DOMAIN = "wortuhr"

CONF_HOST = "host"

MODES = {
    "time": 0,
    "ansage": 1,
    "weekday": 2,
    "date": 3,
    "moonphase": 4,
    "temperature": 5,
    "humidity": 6,
    "pressure": 7,
    "weather": 8,
    #"ext_temperature": 9,
    #"ext_humidity": 10,
    "seconds": 9,
    "ip": 10,
    "test": 11,
    "red": 12,
    "green": 13,
    "blue": 14,
    "white": 15,
    "timer": 16,
    "off": 18,
}

MODE_OPTIONS = {
    "Zeit (Uhr)": 0,
    "Ansage": 1,
    "Wochentag": 2,
    "Datum": 3,
    "Mondphase": 4,
    "Temperatur": 5,
    "Luftfeuchte": 6,
    "Luftdruck": 7,
    "Wetter": 8,
    #"Externe Temperatur": 9,
    #"Externe Luftfeuchte": 10,
    "Sekunden": 9,
    "IP-Adresse": 10,
    "Testmodus": 11,
    "Rot": 12,
    "Grün": 13,
    "Blau": 14,
    "Weiß": 15,
    "Timer": 16,
    "Aus": 18,
}

COLOR_OPTIONS = {
    "Weiß": 0,
    "Rot": 1,
    "Rot 75%": 2,
    "Rot 50%": 3,
    "Orange": 4,
    "Gelb": 5,
    "Gelb 75%": 6,
    "Gelb 50%": 7,
    "Gelb-Grün": 8,
    "Grün": 9,
    "Grün 75%": 10,
    "Grün 50%": 11,
    "Mintgrün": 12,
    "Cyan": 13,
    "Cyan 75%": 14,
    "Cyan 50%": 15,
    "Leicht Blau": 16,
    "Blau": 17,
    "Blau 75%": 18,
    "Blau 50%": 19,
    "Violett": 20,
    "Magenta": 21,
    "Magenta 75%": 22,
    "Magenta 50%": 23,
    "Pink": 24,
}
